/*
 * LCD_Config.h
 *
 *  Created on: Nov 27, 2024
 *      Author: pro
 */

#ifndef HAL_LCD_LCD_CONFIG_H_
#define HAL_LCD_LCD_CONFIG_H_


#include "DIO_Interface.h"

#define LCD_CONTROL_PORT	DIO_PORTB

#define LCD_RS_PIN	DIO_PIN0
#define LCD_RW_PIN	DIO_PIN1
#define LCD_E_PIN	DIO_PIN2

#define LCD_DATA_PORT	DIO_PORTB

#define LCD_D4_PIN	DIO_PIN4
#define LCD_D5_PIN	DIO_PIN5
#define LCD_D6_PIN	DIO_PIN6
#define LCD_D7_PIN	DIO_PIN7

/*Entry_Mode Options
 1- ENTRY_MODE_DECREMENT
 2- ENTRY_MODE_INCREMENT
*/
#define ENTRY_MODE ENTRY_MODE_INCREMENT

/*Cursor Options
 1- DISPLAY_CURSOR_ON_BLINK
 2- DISPLAY_CURSOR_ON_NOBLINK
 3- DISPLAY_CURSOR_OFF
*/
#define DISPLAY_CURSOR		DISPLAY_ON_CURSOR_ON_BLINK

/*Funtion_Set Options
 1- FUNCTION_SET_4BIT_1LINE
 2- FUNCTION_SET_4BIT_2LINE
 3- FUNCTION_SET_8BIT_1LINE
 4- FUNCTION_SET_8BIT_2LINE
*/
#define FUNCTION_SET	FUNCTION_SET_4_BIT_2

#endif /* HAL_LCD_LCD_CONFIG_H_ */
